penelopezone/rubyfmt

src/rubyfmt.rb
This commit updates the lonely operator (&.) handling code to recognise both
the Ruby 2.6 representation (`[:@op, "&.", ...]`) and the earlier
representation (`:"&."`).
=> Fix lonely operator in Ruby 2.6

scripts/test_repo.sh
This commit adds a script to run all of the Ruby files in some external Git repo through rubyfmt, only outputting errors and the paths to the files where they were encountered.
The purpose of the script is to make it easier to throw a whole bunch of code at rubyfmt, so that we can more easily find bugs and uncovered edge-cases.
The issues and PRs I've opened so far were found by running a bunch of thoughtbot repos through rubyfmt (so far: gitsh, factory_bot, and an internal Rails app called Hub), and I've found enough stuff that it seemed useful to turn the awful shell one-liner I was using into a properly reusable script.
=> Add script to test rubyfmt against any Git repo.

fixtures/double_splat_def_actual.rb, fixtures/double_splat_def_expected.rb, src/rubyfmt.rb
Fixes #36 
E.g. on this file would raise an exception:
```rb
def foo(a, **b)
end
```
=> Fix :kwrest_param

scripts/test.sh
It gives contributors a more familiar interface with the diffs the test
produce.
=> Use `git diff --no-index` over `diff(1)`

fixtures/2.5/unnamed_kwrest_param_def_actual.rb, fixtures/2.5/unnamed_kwrest_param_def_expected.rb, fixtures/double_splat_def_actual.rb, fixtures/double_splat_def_expected.rb, scripts/test.sh, src/rubyfmt.rb
As mentioned in #92, I accidentally introduced a bug with #90: test.sh breaks on fixtures/double_splat_def_actual.rb for Ruby 2.4 and below.
I found that older versions of Ripper [had a bug](https://bugs.ruby-lang.org/issues/12387), which I skip around my simply not testing e.g. `def(**)` on Ruby 2.3.
(1st commit fixed a tiny bug in the test script)
=> Fix unnamed kwrest param on older ruby

scripts/test.sh
Doesn't change any behaviour for now, but will make it easier to add more version-specific test cases in the future.
Works for me on macOS, let's see what CI makes of it …
=> Dynamically find compatible test fixtures.

fixtures/nested_command_actual.rb, fixtures/nested_command_expected.rb, src/rubyfmt.rb
There was already code to account for a `command` with a single
`command_call` argument. This commit generalises that to handle a `command`
with a single `command` argument too.
Fixes #104
=> Fix nested commands.

benchmarks/Gemfile, benchmarks/Gemfile.lock, benchmarks/string_escaping/bench.rb, benchmarks/string_escaping/parser_eval.rb, benchmarks/string_escaping/parser_munging.rb, benchmarks/string_escaping/rspec_core_notifications_actual.rb, benchmarks/string_escaping/string_literals_stress_test.rb, src/rubyfmt.rb
Even after Sam's serious improvements to string handling in #87, it still kinda bothered me that we had to do a bunch of work that Ruby must already know how to do.
I spent too much time crawling around in `parse.y` figuring out how Ruby handles character escaping with different string delimiters and, long story short, there doesn't seem to be a way of getting at that information from Ripper without making changes to `parse.y`. Maybe that's worth doing sometime, but since we want to support old Rubies too it wouldn't help immediately.
Still, the Ruby interpreter knows how to properly unescape the content of string literals. So here's a wildly different approach: Instead of trying to parse and re-escape all possible strings ourselves, or coax the information out of Ripper, let's delegate …
=> Use eval for string escaping.

fixtures/string_dvar_actual.rb, fixtures/string_dvar_expected.rb, src/rubyfmt.rb
This commit adds support for interpolated ivars without braces (e.g. `"#@foo"`), and makes the formatting decision that we should always use braces (e.g. `"#{@foo}"`).
=> Add support for string_dvar.

scripts/lint.sh, scripts/test_string_literals.sh
This should allow shellcheck to follow references to other files, and mean
we can remove an ignore directive.
Resolves https://github.com/samphippen/rubyfmt/commit/0c2d20eb2ec219d8c5352f260453084a1708f6c2#comments
=> Run shellcheck with -x

scripts/test_fixtures.sh, src/rubyfmt.rb
This PR updates the test script to run the expected fixtures through `rubyfmt` and compare the output to the original file. The intention is to catch idempotence bugs, i.e. situations where running a file through `rubyfmt` a second time would change the file.
The failures seem to be around whether or not we include parens on a method call. I started looking at fixing them, but Ruby apparently has many, _many_ ways of representing the same call, and it's more than I'll have time to fix today.
Current failures are:
- ~~`fixtures/command_call_raise_expected.rb`~~ (fixed by #117)
- ~~`fixtures/nested_command_expected.rb`~~ (fixed by #117)
- ~~`fixtures/until_while_mod_expected.rb`~~ (fixed on this branch)
Related to #107
=> Test idempotence

README.md
This updates the README to create a `tmp` file and then move that to replace the original file. This is instead of attempting to do an inplace change. The original version from the README does not work as the file is deleted before it has a change to be processed.
I tested this method against a sub-shell approach and found they both ran in about the same amount of time and this seemed like less of a hack. I flip-flopped on this as you can see in my original commit, but I think the `tmp` file approach is more straightforward. Here is both the current tmp file version and the subshell version.
This assumes `$file` is a BASH variable containing the file path
```
rubyfmt "$file" > "${file}.tmp"
mv "${file}.tmp" "$file"
```
vs this subshell method
```
echo "$(rubyfmt $file)" > "$file"
```
This …
=> Update readme to use a tmp file instead of attempting to change inplace

native/Cargo.lock, native/Cargo.toml, native/src/lib.rs
A significant portion of time is spent allocating the `Vec`s in various
rubyfmt data structures. By switching to jemalloc, that cost is
effectively removed, reducing the time to parse a 2kloc file from 140ms
to 105ms on my machine (roughly a 33% improvement)
=> Use jemalloc instead of the system allocator

ext/rubyfmt.c, native/Cargo.lock, native/Cargo.toml, native/src/de.rs, native/src/lib.rs, native/src/ruby.rs, rubyfmt.rb
This removes the json serialization/parsing in favor of linking libruby
directly, and inspecting the ruby objects directly. This is done by just
implementing a minimal `serde::Deserializer` that traverses the Ruby
objects. While this does *not* speed up the creation of the AST, it does
remove the call to `.to_json`, which could be as much as 15% of the
total runtime.
In order to do this, we need to call libruby functions directly. There
are two main libraries for this, Rutie and Helix. Both of these are DSLs
for writing Ruby classes/modules in Rust. Since using those DSLs would
be a bigger change, I opted to just look at their respective bindings to
libruby.
If there is a hard part of using Rust from Ruby, it's that many of
Ruby's important functions (like getting the pointer for a …
=> Operate directly on the ripper output without JSON parsing

native/src/format.rs, native/src/ripper_tree_types.rs
Rather than manually parsing the tag, and losing the debug logging that
occurs for most tags, we re-use the tag parsing from the `def_tag!` macro.
I've also cleaned up the loop in formatting
=> Refactor mlhs handling

native/src/ripper_tree_types.rs
There's no reason this struct needs a custom deserializer. We just need
to tell Serde to use `Default::default` if the field isn't present.
=> `#[derive(Deserialize)]` for `MRHSNewFromArgs`

native/ripper_deserialize/src/lib.rs, native/src/format.rs, native/src/ripper_tree_types.rs
It seems worth it to know if we've got a normal or a heredoc string
literal in the structure itself, rather than encoding that as one field
being `None`. If we do this we can deserialize it the same way we do
untagged enums (doing this required adding multiple field support to our
custom deserialize, which was fairly simple)
It might even be worth having a `NormalStringLiteral` and
`HeredocStringLiteral` (the latter containing the contents as well as
what's currently in a struct with that name), but doing that will
require adding `#[serde(flatten)]` support to tuple structs in Serde
=> Refactor `StringLiteral` deserialization

native/src/ripper_tree_types.rs
This changes the deserialize impl to re-use as much code from serde as
possible. I also missed the "no tag" case in `MLhs`, so I fixed that as
well
=> Refactor `StringContentPart` deserialization

native/src/ripper_tree_types.rs
If we add support for `#[serde(flatten)]` on tuple structs to Serde, we
can derive Deserialize for this struct.
=> Refactor `Deserialize` for `ArgsAddStar`

native/src/format.rs, native/src/lib.rs, native/src/ripper_tree_types.rs
This removes the `#![allow(warnings)]` from that file, and fixes (or
allows) all the warnings that occurred. The most notable were several
cases of `clippy::large_enum_variant`, which triggers when an enum
variant is more than 200 bytes larger than the next largest. This
triggered quite a bit because Expression was 864 bytes! Note that I
generally didn't follow the advice of the lint, and generally opted to
make the structs that were the cause smaller. Expression is now 184
bytes. This was a marginal improvement in CPU time, and a significant
improvement in memory usage.
=> Re-enable warnings in ripper_tree_types.rs, fix them

rubyfmt.vim
Lets one specify the path to `rubyfmt.rb` in vim.
```vim
" in $MYVIMRC
source /Users/mikker/dev/rubyfmt/rubyfmt.vim
let g:rubyfmt_path = '/Users/mikker/dev/rubyfmt/rubyfmt.rb'
```
It's so exciting, @penelopezone – it's working great!
=> Add option to specify path to rubyfmt.rb in vim plugin
